spring.application.name=mycoolapp

#Use wildcard "*" (see here an SQL analogy) to expose all endpoints
#Can also expose individual endpoints with comma-delimit

#individuale, comma delimited list :
#management.endpoints.web.exposure.include=health,info
#all of them, star(*)
management.endpoints.web.exposure.include=*
management.info.env.enabled=true

#Exclude individual delimited endpoints with comma delimited list
#management.endpoints.web.exposure.exclude=health,info

info.app.name=My Spring Boot App
info.app.description=A little app to learn Spring Boot and different features
info.app.version=1.0.0

spring.security.user.name=eliza
spring.security.user.password=luna123

#define own properties
coach.name=Eliza
team.name=Borussia Dortmund

#WEB PROPERTIES
#http server port - by default its 8080
server.port=2121
#http://localhost:2121/my-silly-app/fortune
server.servlet.context-path=/my-silly-app

#Default HTTP session time-out - by default its 30 minutes
#m is short for minutes
server.servlet.session.timeout=15m

#ACTUATOR PROPERTIES
#base path that i want
#http://localhost:2121/my-silly-app/actuator/silly/health
management.endpoints.web.base-path=/actuator/silly

#SECURITY PROPERTIES
#user name and password, as before
