spring.application.name=mycoolapp

#Use wildcard "*" (see here an SQL analogy) to expose all endpoints
#Can also expose individual endpoints with comma-delimit

#individuale, comma delimited list :
#management.endpoints.web.exposure.include=health,info
#all of them, star(*)
management.endpoints.web.exposure.include=*

management.info.env.enabled=true

info.app.name=My Spring Boot App
info.app.description=A little app to learn Spring Boot and different features
info.app.version=1.0.0
