spring.application.name=springcoredome
spring.main.lazy-initialization=true
#The beans are not created until they are needed. Its a GLOBAL thing, so it applies to all classes marked as @Component, @RestController etc..
#If I want this property only for some specific classes - I add @Lazy at the declaration of those classes
